### ISSUE TITLE
Allow exception rules to AutoHangar

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangarIssues#11]
Exceptions to AutoHangar, by player and by grid name / entityID
Examples -- 
Player exception - don't Autohangar this players grids ever

Grid exception - don't Autohangar this gridname/entityid ever

**Comment by BobDaRoss** [comment]
I can only do this via Player/SteamID exceptions.

Grid entityIds can be recreated on grid splits and would be counterproductive.

**Comment by kontu** [comment]
Deal :)

**Comment by BobDaRoss** [comment]
Update:
![asdfasdf](https://user-images.githubusercontent.com/52760019/83083549-07f9ee00-a04c-11ea-82d2-f4ab2f9334ba.PNG)
