### ISSUE TITLE
Feature Request for "Save/Load in Gravity"

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangarIssues#13]
Please allow a configuration for how much gravity is allowed when saving/loading in gravity. This would allow server admins to fine tune based on the worlds and experiences they have (maybe allowing in gravity well but not planet surface, or having some planets with 2.0G but only allowing Hangar'ing up to 1.0G or something)

**Comment by BobDaRoss** [comment]
![asdfasdf](https://user-images.githubusercontent.com/52760019/83086182-ad649000-a053-11ea-8a09-62ef56e46dbf.PNG)
