### ISSUE TITLE
Load near save position

### ISSUE THREAD

**Issue by BobDaRoss** [BobDaRoss/QuantumHangarIssues#15]
This would add the config to load grids near their save position. (not exactly where it was saved)

The main problems with saving it in the exact spot are:
1. Ethical: Do they have to be near the point to load it in? Can they load a station on the moon from halfway across the universe? Do I add a config for this? (This can still be applied to my suggestion above)

2. How to determine if the exact spot is clear? Yes, I'm aware some plugins can detect if there will be a conflict. However, these are mostly admin commands. If I somehow do incorporate a way to properly detect if the area is cleared, what do players do if the area IS occupied? They won't be able to pull their grids out. (a great PVP strat if you ask me)

So this is where I can incorporate something to load it near the save spot. So you will always have a free spot. Near being 1km or less from save position. Static grids would have to follow the same rules. So your asteroid base, if you allow saving of static grids, will not return to the same spot, but perhaps around the roid.

Let me know of your thoughts:

**Comment by kontu** [comment]
I like the idea - maybe make the distance from original location configurable?

And if the area is occupied...hmmm that's tricky. You already block if any enemy is within x distance anyways so pvp isn't a big deal There; but I can see it get annoying for players in factions who hangar at the end of their playtime if their faction mate puts something in that spot. But allowing us to configure the distance from save point could mitigate that

**Comment by BobDaRoss** [comment]
Im going to add some radio buttons to allow three options when it comes to loading from original position.

(Allow players to decide | Force load near player | Force load at original position)

When loading from original position, will add some more configs to customize how close the player has to be to the original point. (To prevent people from loading grids halfway across the galaxy), that and allow players to do exactly that if owners want.

**Comment by kontu** [comment]
> When loading from original position, will add some more configs to customize how close the player has to be to the original point.

Regarding this -- Can you make it pop a GPS point or something for what that original position *is* so players know where they need to go to ungarage?

**Comment by JoozBrorg** [comment]
Atm we use this mod along with Garage block mod, but we could be just using Hangar, and removing the Garage Mod. My only issue with making Grids spawn at/near the area of save is when people are wanting to move from one planet to another or move into deep space they won't be allowed to and will be restricted as to what they can and can't do in the game. And if they would like to move into deep space they would have to grind all there ships and "start over" in a new location. But also in saying that its also a good idea to limit the area of spawning as people could jump load up in Hangar and jump in space pod/Jet pack and run away from future battles.

**Comment by BobDaRoss** [comment]
![Point](https://user-images.githubusercontent.com/52760019/83829794-50975400-a6a9-11ea-968f-932e229a5584.PNG)
