### ISSUE TITLE
Grids Loading Inside Planets

### ISSUE THREAD

**Issue by dylloop** [BobDaRoss/QuantumHangarIssues#16]
Doesnt happen every time but sometimes when players load grids they load in inside an asteroid or planet

**Comment by BobDaRoss** [comment]
I tested this issue extensively with your Hangar configs and world with voxel defender. 

After about 50 tries, I could not get a grid to load in a voxel. I dug under a planet and even into centers of asteroids. Spawned large and small grids none of which spawned in an asteroid or planet. Multiple times, I simply got "Not enough room to spawn grid." The only thing left from the equation is your plugins. I did not download and test them all. This seems to not be a Hangar issue. 

![2020-05-18-13-51-10-361](https://user-images.githubusercontent.com/52760019/82251009-193b5000-9912-11ea-8f1d-0f5b8a98863e.png)

If this issue persists with more people, ill have to look into it more. However, from my tests, this is not a hangar issue. As everything performed normally for me.
