### ISSUE TITLE
Spawn point linked to respawn point.

### ISSUE THREAD

**Issue by Fat0Fly** [BobDaRoss/QuantumHangarIssues#17]
To prevent the players to misuse plugin for the "grid teleportation" purposes:
Option 1. 
Bind spawn/despawn location to a specific "block".

Option 2. 
Bind spawn/despawn location to a specific area.

In both options players will only be able to spawn their grids where they store them - on the same location. Concept is similar to SE vanilla respawn system, where players can not chose respawn point, and they are spawning near their last used spawn point. 

I believe that it can be done with simple instruction for script to save the grid at defined "sub folders". Every spawn area/block should have separate folder and it only contains grids stored at that area/block.

Tip-Top job on the plugin! Respect!
FatFly - Upside Down Community

**Comment by BobDaRoss** [comment]
So I've been thinking about this. To avoid a complete re-write of this plugin, I can do the following:

1. Implement configurable loading and saving zones. 
You can already create zones but only one per type in v2.2.1 I'm going to be implementing the option to create as many zones as you want via GPS coords.

2. Implement loading from original position discussed in #15 
This would restrict the player from loading them wherever they want, but only to where they were saved from. This would be similar to what you want but not exact.

I'm just trying to avoid a complete re-write. I know it may sound easy but I would be looking at a day or 2 of work to redo. Id essentially be starting fresh.

The above features would be added for free as they suit the general end-users, however if you are wanting a more rigid and suitable system to match exactly your server needs I can create a new plugin just for you and your server (for price) I would give you complete source access to this new plugin so your own devs can make modifications and whatnot. Hangar is just too big to backtrack and implement this into a configurable style.

Let me know what you think!

**Comment by Fat0Fly** [comment]
Sounds perfect! On of my team mates mentioned a small feature that would be useful in case player forgets where he did it - a notification after unsuccessful command would be neat :)

Thanks for your time and effort.

**Comment by BobDaRoss** [comment]
Little Update:
![hmmmmmmmm](https://user-images.githubusercontent.com/52760019/82986975-6d060300-9fbc-11ea-95ad-5806a1c38388.PNG)

Here you can add as many zones you want and customize their save/load/radius restrictions.

I have yet to add load near original position config, but that is on the list to be added soon.

**Comment by BobDaRoss** [comment]
![Point](https://user-images.githubusercontent.com/52760019/83829811-61e06080-a6a9-11ea-8a7f-4c7c794b5c47.PNG)
