### ISSUE TITLE
Feature Request: Hook to ALE Gridbackup to trigger on save / load

### ISSUE THREAD

**Issue by kontu** [BobDaRoss/QuantumHangarIssues#24]
While I know there's a ton of code in to deal with duplication / deduplication, and it's working fabulously, I'd feel more comfortable training new staff and having an extra layer of defense if Quantum Hangar could run `!gridbackup save` on a grid whenever it is saved to the hangar or loaded to the hangar. This gives server admins an extra place they can reference if something goes south; or if a player loads a grid from Hangar and then some cleanup autocommand nabs it right away, this ensures there's always an easy to access a copy of the grid

**Comment by LordTylus** [comment]
Currently I dont have any public API to have !gridbackup save being triggered from an other plugin, unless you indeed run a command like essentials does.

However if you are planning to implement it I could also move the for saving a single grid elsewhere so you can directly invoke it on GridBackup. 

Up to you just lemme know what your plan is :-)

**Comment by BobDaRoss** [comment]
It should be pretty easy to access via reflection right?

**Comment by LordTylus** [comment]
Well not right now,

As the code is inside the code to Trigger it is inside the Command class. Which only has an instance while a command is executed.

However I could move the Code to do it to the Plugin Class itself.

And you could just call it like I connect to BlockLimiter via PCU Transferrer here:

https://github.com/LordTylus/SE-Torch-Plugin-ALE-PcuTransferrer/blob/e7c1203e7fde93f9bfa4a3eac33a0c7028b89383/ALE-PcuTransferrer/GridManagerPlugin.cs#L98-L127

Will refactor it for you real quick, then you can use it if the server has the latest version of the plugin installed.

**Comment by LordTylus** [comment]
I added a Method you should be able to call from your Plugin

of course you have to check first if GridBackup is installed. How that works you an see the link I posted above

https://github.com/LordTylus/SE-Torch-Plugin-ALE-GridBackup/blob/1a974c3195a26f3b4bc2146709f24e789971c1f2/ALE-GridBackup/GridBackupPlugin.cs#L232-L274

**Comment by BobDaRoss** [comment]
Awesome! Ill add that tonight and fix the other little bugs.

**Comment by BobDaRoss** [comment]
@LordTylus  So it looks like im invoking your method right, however, it doesn't show in my backup list. Not throwing any errors either.

```            if (Plugin.GridBackup != null)
            {

                MyAPIGateway.Utilities.InvokeOnGameThread(delegate
                {
                    try
                    {
                        Plugin.GridBackup.GetType().GetMethod("BackupGridsManually", System.Reflection.BindingFlags.Public | System.Reflection.BindingFlags.Instance).Invoke(Plugin.GridBackup, new object[] { grids, null, null, null });
                        Log.Warn("Successfully BackedUp grid!");
                    }
                    catch (Exception e)
                    {
                        Log.Warn(e);
                    }
                });

            }
```

**Comment by BobDaRoss** [comment]
So it seems to work now. Just not invoking on main game thread anymore. This could be a problem, but I've put some catches in place to hopefully prevent the collection is modified stuff.
