### ISSUE TITLE
players with bugged hangars

### ISSUE THREAD

**Issue by jrnesbit** [BobDaRoss/QuantumHangarIssues#27]
daschamp18Today at 9:28 PM
it says grid does not exist
but when i do hangar list it shows them

then another guy that cant pull stuff out is saying 
I tried loading i_Float it said talk to admin to check logs and then i tried laoding care package -- large cargo with some stuff in it

i cant access anyones list that i try  it always say exception thrown by the target of invocation.

right now id just liek to know if theres quick way to repair these guys hangars

**Comment by BobDaRoss** [comment]
Yeah that player might still be bugged from previous bug.

"!hangar remove [Id]" to try and remove bugged grid.

If not load all grids you can from that players folder then remove folder entirely. Will fix it 100%

**Comment by jrnesbit** [comment]
still getting "exception has been thrown by the target of an invocation" when !hangarmod list name   some of these players   also
