### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jrnesbit** [BobDaRoss/QuantumHangarIssues#30]
had another guys hangar grids bug out yesterday (same guy from the other day)  
today i go to !hangarmod list "Sir Sloth"   and it gives me that exception has been thrown by the target of an invocation

i just got the new update 20mins ago.    still throwing  exceptions but im wondering if thats becasue that players file is corrupted. 
do I need to wipe some corrupted files and where can i find them
[Torch-2020-07-17.log](https://github.com/BobDaRoss/QuantumHangarIssues/files/4941843/Torch-2020-07-17.log)
[Torch-2020-07-18.log](https://github.com/BobDaRoss/QuantumHangarIssues/files/4941844/Torch-2020-07-18.log)

**Comment by BobDaRoss** [comment]
There not corrupted files. Just issues with promote levels. Im not sure why its still throwing it

**Comment by jrnesbit** [comment]
you're welcome to see my files and test it on my server if u want
