### ISSUE TITLE
Hangar not detecting roles above Scripter

### ISSUE THREAD

**Issue by Neimoh** [BobDaRoss/QuantumHangarIssues#32]
We're having issues after a wipe with the hangar not giving access to scripter slots if players are set to anything other than Scripter role. I have 2 Admins so far at level 4 in game and it won't open up their hangar slots unless we demote them to actual Scripter and save. Then the hangar reports correctly. Once we promote them back to Admin they lose the Scripter slots.

**Comment by BobDaRoss** [comment]
Hmm ill look into this
