### ISSUE TITLE
Feature request: Add tag to name of the grid that prevents autohangar

### ISSUE THREAD

**Issue by OwendB1** [BobDaRoss/QuantumHangarIssues#9]
So what this would do is that it will add the possibility for players to prevent autohangar from putting their grids into the hangar. It would be nice if it were possible to configure the amount of tags that the faction can use to prevent hangaring i.e. let each faction use 4 tags, 1 for a main production ship and 3 utility ships (Welders, miners etc.).

**Comment by BobDaRoss** [comment]
The main purpose of autohangar is to autohangar grids that have been abandoned by players. Maybe they left the server for over 20 days or whatnot. When we start putting exceptions like that in, you might as well just leave it off. I understand where you are going at, but when 3/4 of a faction hasn't been on, the online ones will move to more online factions or repurpose the old grids. I've already added Autohangar configs to ignore certain types of grids such as stations.

Im not saying no to this request, just putting it near the bottom of my list unless more people care to vote/voice their opinions on this. It just doesn't match what I think AutoHangar is used for IMO. It's just an odd request for a work to benefit ratio.

**Comment by OwendB1** [comment]
Then we'll just stick to the previous request and dump this one :)
